name: nightly build at 8:15 pm

on:
  push: 
  schedule:
    - cron: '15 20 * * *'

jobs:
  nightly_build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.3

       #Cache the dependecies to speed up execution.Changes visible after first execution.
      - name: Cache the Maven packages to speed up build
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2  

      #Run the Junit test,continue even if a single test fails in it
      - name: Run Unit Tests
        continue-on-error: true
        run: mvn test -Dtest=CalcTest
        working-directory: ./demo

     #Run the Api tests,continue even if a single test fails in it
      - name: Run Api Tests
        continue-on-error: true
        run: mvn test -Dtest=apiTest
        working-directory: ./demo

      #Build a jar file
      - name: Build with Maven
        run: mvn -DskipTests -B package --no-transfer-progress --file ./demo/pom.xml
       # working-directory: ./demo

      #upload jar file to workflow
      - uses: actions/upload-artifact@master
        with:
          name: demo.jar
          path: ./demo/target/*demo*.jar
