name: run unit tests of feature branches

on:
  push:
    branches: 
      'feature/*'


jobs:
  run-unit-test:
    runs-on: ubuntu-latest


    steps: 
      - name: Checkout
      - uses: actions/checkout@v4
      - name: SetUp Java
      - uses: actions/setup-java@v4
        with:
          java-version: '17'

      - name: run unit test
        run: mvn -B package --file pom.xml
