name: run unit tests of feature branches

on:
  push:
    branches: 
      'feature/*'


jobs:
  run-unit-test:
    runs-on: ubuntu-latest


    steps: 
      - name: Checkout
        uses: actions/checkout@v3.3.0
      - name: Set up JDK 14
        uses: actions/setup-java@v3.14.1
        with:
           java-version: 17

      - name: run unit test
        run: mvn -B package --file pom.xml
