name: nightly build at 8:15 pm

on:
  push: 
  schedule:
    - cron: '15 20 * * *'

jobs:
  nightly_build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0


      - name: Run Unit Tests
        continue-on-error: true
        run: mvn test
        working-directory: ./demo

      - name: Build with Maven
        run: mvn -DskipTests -B package --no-transfer-progress --file ./demo/pom.xml
       # working-directory: ./demo

      - uses: actions/upload-artifact@master
        with:
          name: target.war
          path: ./demo/target/*demo*.war
